import one from "../../assets/pictures/one.jpg";
import two from"../../assets/pictures/two.jpg";

const record=[
    {
      "id": 1,
      "src": one,
      "alt": "Thumbnail 1",
      "name": "Product Name 1",
      "brand": "Brand 1",
      "model": "Model 1",
      "availability": "Only 2 in Stock",
      "originalPrice": 800.00,
    "discountedPrice": 600.72,
      "description": "Description for product 1Lorem ipsum dolor sit amet consectetur adipisicing elit. Quas harum facilis est neque possimus assumenda quo aliquam, repudiandae voluptatem ad id porro nihil magni a ipsam, rerum veritatis excepturi quis esse iusto vero cumque voluptate. Placeat doloribus possimus dicta molestiae, minima dolorem totam fugiat molestias ad nesciunt quibusdam natus dolores dolor perferendis perspiciatis quisquam odit voluptatum beatae cumque inventore. Dolor, suscipit? A repellendus suscipit nemo, ut consectetur velit placeat optio blanditiis veritatis molestias perspiciatis temporibus amet aut. Dolores unde, ad quam, sunt architecto vitae laboriosam error labore rem dignissimos eveniet? Quisquam dolor nemo quia porro officia rerum ratione nostrum officiis!",
      "specification": "Specification for product 1Lorem ipsum dolor sit amet consectetur adipisicing elit. Quas harum facilis est neque possimus assumenda quo aliquam, repudiandae voluptatem ad id porro nihil magni a ipsam, rerum veritatis excepturi quis esse iusto vero cumque voluptate. Placeat doloribus possimus dicta molestiae, minima dolorem totam fugiat molestias ad nesciunt quibusdam natus dolores dolor perferendis perspiciatis quisquam odit voluptatum beatae cumque inventore. Dolor, suscipit? A repellendus suscipit nemo, ut consectetur velit placeat optio blanditiis veritatis molestias perspiciatis temporibus amet aut. Dolores unde, ad quam, sunt architecto vitae laboriosam error labore rem dignissimos eveniet? Quisquam dolor nemo quia porro officia rerum ratione nostrum officiis!",
      "reviews": "Reviews for product 1Lorem ipsum dolor sit amet consectetur adipisicing elit. Quas harum facilis est neque possimus assumenda quo aliquam, repudiandae voluptatem ad id porro nihil magni a ipsam, rerum veritatis excepturi quis esse iusto vero cumque voluptate. Placeat doloribus possimus dicta molestiae, minima dolorem totam fugiat molestias ad nesciunt quibusdam natus dolores dolor perferendis perspiciatis quisquam odit voluptatum beatae cumque inventore. Dolor, suscipit? A repellendus suscipit nemo, ut consectetur velit placeat optio blanditiis veritatis molestias perspiciatis temporibus amet aut. Dolores unde, ad quam, sunt architecto vitae laboriosam error labore rem dignissimos eveniet? Quisquam dolor nemo quia porro officia rerum ratione nostrum officiis!",
      "details": [
        "Gen5 AI Processor with AI Picture Pro & AI 4K Upscaling",
        "Pixel Dimming, Perfect Black, 100% Color Fidelity & Color Volume",
        "Feature 3 of product Hands-free Voice Control, Always Ready",
        "Dolby Vision IQ with Precision Detail, Dolby Atmos, Filmmaker Mode",
        "Eye Comfort Display: Low-Blue Light, Flicker-Free"
      ]
    },
    {
      "id": 2,
      "src": two,
      "alt": "Thumbnail 2",
      "name": "Product Name 2",
      "brand": "Brand 2",
      "model": "Model 2",
      "availability": "Out of Stock",
      "originalPrice": 900.00,
      "discountedPrice": 500.72,
      "description": "Description for product 3Lorem ipsum dolor sit amet consectetur adipisicing elit. Quas harum facilis est neque possimus assumenda quo aliquam, repudiandae voluptatem ad id porro nihil magni a ipsam, rerum veritatis excepturi quis esse iusto vero cumque voluptate. Placeat doloribus possimus dicta molestiae, minima dolorem totam fugiat molestias ad nesciunt quibusdam natus dolores dolor perferendis perspiciatis quisquam odit voluptatum beatae cumque inventore. Dolor, suscipit? A repellendus suscipit nemo, ut consectetur velit placeat optio blanditiis veritatis molestias perspiciatis temporibus amet aut. Dolores unde, ad quam, sunt architecto vitae laboriosam error labore rem dignissimos eveniet? Quisquam dolor nemo quia porro officia rerum ratione nostrum officiis,Specification for product 3Lorem ipsum dolor sit amet consectetur adipisicing elit. Quas harum facilis est neque possimus assumenda quo aliquam, repudiandae voluptatem ad id porro nihil magni a ipsam, rerum veritatis excepturi quis esse iusto vero cumque voluptate. Placeat doloribus possimus dicta molestiae, minima dolorem totam fugiat molestias ad nesciunt quibusdam natus dolores dolor perferendis perspiciatis quisquam odit voluptatum beatae cumque inventore. Dolor, suscipit? A repellendus suscipit nemo, ut consectetur velit placeat optio blanditiis veritatis molestias perspiciatis temporibus amet aut. Dolores unde, ad quam, sunt architecto vitae laboriosam error labore rem dignissimos eveniet? Quisquam dolor nemo quia porro officia rerum ratione nostrum officiis! ",
      "specification": "Specification for product 3Lorem ipsum dolor sit amet consectetur adipisicing elit. Quas harum facilis est neque possimus assumenda quo aliquam, repudiandae voluptatem ad id porro nihil magni a ipsam, rerum veritatis excepturi quis esse iusto vero cumque voluptate. Placeat doloribus possimus dicta molestiae, minima dolorem totam fugiat molestias ad nesciunt quibusdam natus dolores dolor perferendis perspiciatis quisquam odit voluptatum beatae cumque inventore. Dolor, suscipit? A repellendus suscipit nemo, ut consectetur velit placeat optio blanditiis veritatis molestias perspiciatis temporibus amet aut. Dolores unde, ad quam, sunt architecto vitae laboriosam error labore rem dignissimos eveniet? Quisquam dolor nemo quia porro officia rerum ratione nostrum officiis,Specification for product 3Lorem ipsum dolor sit amet consectetur adipisicing elit. Quas harum facilis est neque possimus assumenda quo aliquam, repudiandae voluptatem ad id porro nihil magni a ipsam, rerum veritatis excepturi quis esse iusto vero cumque voluptate. Placeat doloribus possimus dicta molestiae, minima dolorem totam fugiat molestias ad nesciunt quibusdam natus dolores dolor perferendis perspiciatis quisquam odit voluptatum beatae cumque inventore. Dolor, suscipit? A repellendus suscipit nemo, ut consectetur velit placeat optio blanditiis veritatis molestias perspiciatis temporibus amet aut. Dolores unde, ad quam, sunt architecto vitae laboriosam error labore rem dignissimos eveniet? Quisquam dolor nemo quia porro officia rerum ratione nostrum officiis!",
      "reviews": "Reviews for product 3Lorem ipsum dolor sit amet consectetur adipisicing elit. Quas harum facilis est neque possimus assumenda quo aliquam, repudiandae voluptatem ad id porro nihil magni a ipsam, rerum veritatis excepturi quis esse iusto vero cumque voluptate. Placeat doloribus possimus dicta molestiae, minima dolorem totam fugiat molestias ad nesciunt quibusdam natus dolores dolor perferendis perspiciatis quisquam odit voluptatum beatae cumque inventore. Dolor, suscipit? A repellendus suscipit nemo, ut consectetur velit placeat optio blanditiis veritatis molestias perspiciatis temporibus amet aut. Dolores unde, ad quam, sunt architecto vitae laboriosam error labore rem dignissimos eveniet? Quisquam dolor nemo quia porro officia rerum ratione nostrum officiis,Specification for product 3Lorem ipsum dolor sit amet consectetur adipisicing elit. Quas harum facilis est neque possimus assumenda quo aliquam, repudiandae voluptatem ad id porro nihil magni a ipsam, rerum veritatis excepturi quis esse iusto vero cumque voluptate. Placeat doloribus possimus dicta molestiae, minima dolorem totam fugiat molestias ad nesciunt quibusdam natus dolores dolor perferendis perspiciatis quisquam odit voluptatum beatae cumque inventore. Dolor, suscipit? A repellendus suscipit nemo, ut consectetur velit placeat optio blanditiis veritatis molestias perspiciatis temporibus amet aut. Dolores unde, ad quam, sunt architecto vitae laboriosam error labore rem dignissimos eveniet? Quisquam dolor nemo quia porro officia rerum ratione nostrum officiis!",
      "details": [
        "Gen5 AI Processor with AI Picture Pro & AI 4K Upscaling",
        "Pixel Dimming, Perfect Black, 100% Color Fidelity & Color Volume",
        "Feature 3 of product Hands-free Voice Control, Always Ready",
        "Dolby Vision IQ with Precision Detail, Dolby Atmos, Filmmaker Mode",
        "Eye Comfort Display: Low-Blue Light, Flicker-Free"
      ]
    },
    {
        "id": 3,
        "src": two,
        "alt": "Thumbnail 3",
        "name": "Product Name 3",
        "brand": "Brand 3",
        "model": "Model 3",
        "availability": "In Stock",
        "originalPrice": 1000.00,
      "discountedPrice": 800.72,
        "description": "Description for product 3Lorem ipsum dolor sit amet consectetur adipisicing elit. Quas harum facilis est neque possimus assumenda quo aliquam, repudiandae voluptatem ad id porro nihil magni a ipsam, rerum veritatis excepturi quis esse iusto vero cumque voluptate. Placeat doloribus possimus dicta molestiae, minima dolorem totam fugiat molestias ad nesciunt quibusdam natus dolores dolor perferendis perspiciatis quisquam odit voluptatum beatae cumque inventore. Dolor, suscipit? A repellendus suscipit nemo, ut consectetur velit placeat optio blanditiis veritatis molestias perspiciatis temporibus amet aut. Dolores unde, ad quam, sunt architecto vitae laboriosam error labore rem dignissimos eveniet? Quisquam dolor nemo quia porro officia rerum ratione nostrum officiis,Specification for product 3Lorem ipsum dolor sit amet consectetur adipisicing elit. Quas harum facilis est neque possimus assumenda quo aliquam, repudiandae voluptatem ad id porro nihil magni a ipsam, rerum veritatis excepturi quis esse iusto vero cumque voluptate. Placeat doloribus possimus dicta molestiae, minima dolorem totam fugiat molestias ad nesciunt quibusdam natus dolores dolor perferendis perspiciatis quisquam odit voluptatum beatae cumque inventore. Dolor, suscipit? A repellendus suscipit nemo, ut consectetur velit placeat optio blanditiis veritatis molestias perspiciatis temporibus amet aut. Dolores unde, ad quam, sunt architecto vitae laboriosam error labore rem dignissimos eveniet? Quisquam dolor nemo quia porro officia rerum ratione nostrum officiis! ",
        "specification": "Specification for product 3Lorem ipsum dolor sit amet consectetur adipisicing elit. Quas harum facilis est neque possimus assumenda quo aliquam, repudiandae voluptatem ad id porro nihil magni a ipsam, rerum veritatis excepturi quis esse iusto vero cumque voluptate. Placeat doloribus possimus dicta molestiae, minima dolorem totam fugiat molestias ad nesciunt quibusdam natus dolores dolor perferendis perspiciatis quisquam odit voluptatum beatae cumque inventore. Dolor, suscipit? A repellendus suscipit nemo, ut consectetur velit placeat optio blanditiis veritatis molestias perspiciatis temporibus amet aut. Dolores unde, ad quam, sunt architecto vitae laboriosam error labore rem dignissimos eveniet? Quisquam dolor nemo quia porro officia rerum ratione nostrum officiis,Specification for product 3Lorem ipsum dolor sit amet consectetur adipisicing elit. Quas harum facilis est neque possimus assumenda quo aliquam, repudiandae voluptatem ad id porro nihil magni a ipsam, rerum veritatis excepturi quis esse iusto vero cumque voluptate. Placeat doloribus possimus dicta molestiae, minima dolorem totam fugiat molestias ad nesciunt quibusdam natus dolores dolor perferendis perspiciatis quisquam odit voluptatum beatae cumque inventore. Dolor, suscipit? A repellendus suscipit nemo, ut consectetur velit placeat optio blanditiis veritatis molestias perspiciatis temporibus amet aut. Dolores unde, ad quam, sunt architecto vitae laboriosam error labore rem dignissimos eveniet? Quisquam dolor nemo quia porro officia rerum ratione nostrum officiis!",
        "reviews": "Reviews for product 3Lorem ipsum dolor sit amet consectetur adipisicing elit. Quas harum facilis est neque possimus assumenda quo aliquam, repudiandae voluptatem ad id porro nihil magni a ipsam, rerum veritatis excepturi quis esse iusto vero cumque voluptate. Placeat doloribus possimus dicta molestiae, minima dolorem totam fugiat molestias ad nesciunt quibusdam natus dolores dolor perferendis perspiciatis quisquam odit voluptatum beatae cumque inventore. Dolor, suscipit? A repellendus suscipit nemo, ut consectetur velit placeat optio blanditiis veritatis molestias perspiciatis temporibus amet aut. Dolores unde, ad quam, sunt architecto vitae laboriosam error labore rem dignissimos eveniet? Quisquam dolor nemo quia porro officia rerum ratione nostrum officiis,Specification for product 3Lorem ipsum dolor sit amet consectetur adipisicing elit. Quas harum facilis est neque possimus assumenda quo aliquam, repudiandae voluptatem ad id porro nihil magni a ipsam, rerum veritatis excepturi quis esse iusto vero cumque voluptate. Placeat doloribus possimus dicta molestiae, minima dolorem totam fugiat molestias ad nesciunt quibusdam natus dolores dolor perferendis perspiciatis quisquam odit voluptatum beatae cumque inventore. Dolor, suscipit? A repellendus suscipit nemo, ut consectetur velit placeat optio blanditiis veritatis molestias perspiciatis temporibus amet aut. Dolores unde, ad quam, sunt architecto vitae laboriosam error labore rem dignissimos eveniet? Quisquam dolor nemo quia porro officia rerum ratione nostrum officiis!",
        "details": [
          "Gen5 AI Processor with AI Picture Pro & AI 4K Upscaling",
        "Pixel Dimming, Perfect Black, 100% Color Fidelity & Color Volume",
        "Feature 3 of product Hands-free Voice Control, Always Ready",
        "Dolby Vision IQ with Precision Detail, Dolby Atmos, Filmmaker Mode",
        "Eye Comfort Display: Low-Blue Light, Flicker-Free"
        ]
      },
      {
        "id": 4,
        "src": two,
        "alt": "Thumbnail 4",
        "name": "Product Name 4",
        "brand": "Brand 4",
        "model": "Model 4",
        "availability": "In Stock",
        "originalPrice": 700.00,
      "discountedPrice": 600.72,
      "description": "Description for product 3Lorem ipsum dolor sit amet consectetur adipisicing elit. Quas harum facilis est neque possimus assumenda quo aliquam, repudiandae voluptatem ad id porro nihil magni a ipsam, rerum veritatis excepturi quis esse iusto vero cumque voluptate. Placeat doloribus possimus dicta molestiae, minima dolorem totam fugiat molestias ad nesciunt quibusdam natus dolores dolor perferendis perspiciatis quisquam odit voluptatum beatae cumque inventore. Dolor, suscipit? A repellendus suscipit nemo, ut consectetur velit placeat optio blanditiis veritatis molestias perspiciatis temporibus amet aut. Dolores unde, ad quam, sunt architecto vitae laboriosam error labore rem dignissimos eveniet? Quisquam dolor nemo quia porro officia rerum ratione nostrum officiis,Specification for product 3Lorem ipsum dolor sit amet consectetur adipisicing elit. Quas harum facilis est neque possimus assumenda quo aliquam, repudiandae voluptatem ad id porro nihil magni a ipsam, rerum veritatis excepturi quis esse iusto vero cumque voluptate. Placeat doloribus possimus dicta molestiae, minima dolorem totam fugiat molestias ad nesciunt quibusdam natus dolores dolor perferendis perspiciatis quisquam odit voluptatum beatae cumque inventore. Dolor, suscipit? A repellendus suscipit nemo, ut consectetur velit placeat optio blanditiis veritatis molestias perspiciatis temporibus amet aut. Dolores unde, ad quam, sunt architecto vitae laboriosam error labore rem dignissimos eveniet? Quisquam dolor nemo quia porro officia rerum ratione nostrum officiis! ",
      "specification": "Specification for product 3Lorem ipsum dolor sit amet consectetur adipisicing elit. Quas harum facilis est neque possimus assumenda quo aliquam, repudiandae voluptatem ad id porro nihil magni a ipsam, rerum veritatis excepturi quis esse iusto vero cumque voluptate. Placeat doloribus possimus dicta molestiae, minima dolorem totam fugiat molestias ad nesciunt quibusdam natus dolores dolor perferendis perspiciatis quisquam odit voluptatum beatae cumque inventore. Dolor, suscipit? A repellendus suscipit nemo, ut consectetur velit placeat optio blanditiis veritatis molestias perspiciatis temporibus amet aut. Dolores unde, ad quam, sunt architecto vitae laboriosam error labore rem dignissimos eveniet? Quisquam dolor nemo quia porro officia rerum ratione nostrum officiis,Specification for product 3Lorem ipsum dolor sit amet consectetur adipisicing elit. Quas harum facilis est neque possimus assumenda quo aliquam, repudiandae voluptatem ad id porro nihil magni a ipsam, rerum veritatis excepturi quis esse iusto vero cumque voluptate. Placeat doloribus possimus dicta molestiae, minima dolorem totam fugiat molestias ad nesciunt quibusdam natus dolores dolor perferendis perspiciatis quisquam odit voluptatum beatae cumque inventore. Dolor, suscipit? A repellendus suscipit nemo, ut consectetur velit placeat optio blanditiis veritatis molestias perspiciatis temporibus amet aut. Dolores unde, ad quam, sunt architecto vitae laboriosam error labore rem dignissimos eveniet? Quisquam dolor nemo quia porro officia rerum ratione nostrum officiis!",
      "reviews": "Reviews for product 3Lorem ipsum dolor sit amet consectetur adipisicing elit. Quas harum facilis est neque possimus assumenda quo aliquam, repudiandae voluptatem ad id porro nihil magni a ipsam, rerum veritatis excepturi quis esse iusto vero cumque voluptate. Placeat doloribus possimus dicta molestiae, minima dolorem totam fugiat molestias ad nesciunt quibusdam natus dolores dolor perferendis perspiciatis quisquam odit voluptatum beatae cumque inventore. Dolor, suscipit? A repellendus suscipit nemo, ut consectetur velit placeat optio blanditiis veritatis molestias perspiciatis temporibus amet aut. Dolores unde, ad quam, sunt architecto vitae laboriosam error labore rem dignissimos eveniet? Quisquam dolor nemo quia porro officia rerum ratione nostrum officiis,Specification for product 3Lorem ipsum dolor sit amet consectetur adipisicing elit. Quas harum facilis est neque possimus assumenda quo aliquam, repudiandae voluptatem ad id porro nihil magni a ipsam, rerum veritatis excepturi quis esse iusto vero cumque voluptate. Placeat doloribus possimus dicta molestiae, minima dolorem totam fugiat molestias ad nesciunt quibusdam natus dolores dolor perferendis perspiciatis quisquam odit voluptatum beatae cumque inventore. Dolor, suscipit? A repellendus suscipit nemo, ut consectetur velit placeat optio blanditiis veritatis molestias perspiciatis temporibus amet aut. Dolores unde, ad quam, sunt architecto vitae laboriosam error labore rem dignissimos eveniet? Quisquam dolor nemo quia porro officia rerum ratione nostrum officiis!",
        "details": [
          "Gen5 AI Processor with AI Picture Pro & AI 4K Upscaling",
          "Pixel Dimming, Perfect Black, 100% Color Fidelity & Color Volume",
          "Feature 3 of product Hands-free Voice Control, Always Ready",
          "Dolby Vision IQ with Precision Detail, Dolby Atmos, Filmmaker Mode",
          "Eye Comfort Display: Low-Blue Light, Flicker-Free"
        ]
      }
  ]
  export default record;
  