import { Lipstick } from "../../assets/assets";

const productDetails = [
  {
    id: 1,
    name: "Moisture Matte Long Stay",
    price: 560,
    image: Lipstick,
    rating: 4,
    reviews: 36,
    imageUrl: " ",
    discount: 20,
    category: "Eyeliner",
    color: "bg-pink-700",
    dresStyle: "Casuals",
    brands: "Lakme",
    shade: "Pink",
    material: "Soft", 
    quantity:1,
  },
  {
    id: 13,
    name: "Moisture Matte Long ",
    price: 160,
    image: Lipstick,
    rating: 4,
    reviews: 36,
    imageUrl: " ",
    discount: 20,
    category: "Eyeliner",
    color: "bg-pink-700",
    dresStyle: "Casuals",
    brands: "Lakme",
    shade: "Pink",
    material: "Soft", 
    quantity:1,
  },
  {
    id: 2,
    name: "Moisture Matte Long Stay",
    price: 400,
    image: Lipstick,
    rating: 3,
    reviews: 36,
    imageUrl: " ",
    category: "Lipstick",
    color: "bg-yellow-700",
    dresStyle: "Formals",
    brands: "HudaBeauty",
    shade: "Pink",
    material: "Hard",
    discount: 10,
    quantity:1,
  },
  {
    id: 3,
    name: "Moisture Matte Long Stay",
    price: 600,
    image: Lipstick,
    rating: 2,
    reviews: 36,
    imageUrl: " ",
    category: "Kajal",
    color: "bg-red-700",
    dresStyle: "Party",
    brands: "Renne",
    shade: "Rose",
    discount: 10,
    material: "Hard",
    quantity:1,
  },
  {
    id: 4,
    name: "Moisture Matte Long Stay",
    price: 200,
    image: Lipstick,
    rating: 1,
    reviews: 36,
    imageUrl: " ",
    category: "Mascara",
    color: "bg-pink-500",
    dresStyle: "Gym",
    brands: "Nars",
    shade: "Pink",
    discount: 20,
    material: "Soft",
    quantity:1,
  },
  {
    id: 5,
    name: "Moisture Matte Long Stay",
    price: 300,
    image: Lipstick,
    rating: 2,
    reviews: 36,
    imageUrl: " ",
    category: "Foundation",
    color: "bg-blue-500",
    dresStyle: "Casuals",
    brands: "Ravlon",
    shade: "Dark Pink",
    discount: 20,
    material: "Soft",
    quantity:1,
  },
  {
    id: 6,
    name: "Moisture Matte Long Stay",
    price: 320,
    image: Lipstick,
    rating: 3,
    reviews: 36,
    imageUrl: " ",
    category: "Eyeliner",
    color: "bg-red-500",
    dresStyle: "Formals",
    brands: "Sugar",
    shade: "Rose",
    discount: 20,
    material: "Soft",
    quantity:1,
  },
  {
    id: 7,
    name: "Moisture Matte Long Stay",
    price: 450,
    image: Lipstick,
    rating: 5,
    reviews: 36,
    imageUrl: " ",
    category: "Mascara",
    color: "bg-green-500",
    dresStyle: "Gym",
    brands: "MAC",
    shade: "Rose",
    discount: 10,
    material: "Soft",
    quantity:1,
  },
  {
    id: 8,
    name: "Moisture Matte Long Stay",
    price: 190,
    image: Lipstick,
    rating: 4,
    reviews: 36,
    imageUrl: " ",
    category: "Lipstick",
    color: "bg-yellow-500",
    dresStyle: "Party",
    brands: "AVEDA",
    shade: "Pink",
    discount: 10,
    material: "Soft",
    quantity:1,
  },
  {
    id: 9,
    name: "Moisture Matte Long Stay",
    price: 199,
    image: Lipstick,
    rating: 4,
    reviews: 36,
    imageUrl: " ",
    category: "Eyeliner",
    color: "bg-pink-400",
    shade: "Pink",
    dresStyle: "Gym",
    brands: "Lakme",
    discount: 20,
    material: "Hard",
    quantity:1,
  },
  {
    id: 10,
    name: "Moisture Matte Long Stay",
    price: 399,
    image: Lipstick,
    rating: 4,
    reviews: 36,
    imageUrl: " ",
    category: "Eyeliner",
    color: "bg-pink-400",
    shade: "Pink",
    dresStyle: "Gym",
    brands: "Lakme",
    discount: 20,
    material: "Hard",
    quantity:1,
  },
  {
    id: 11,
    name: "Moisture Matte Long Stay",
    price: 699,
    image: Lipstick,
    rating: 4,
    reviews: 36,
    imageUrl: " ",
    category: "Eyeliner",
    color: "bg-pink-400",
    shade: "Pink",
    dresStyle: "Gym",
    brands: "Lakme",
    discount: 20,
    material: "Hard",
    quantity:1,
  },
  {
    id: 12,
    name: "Moisture Matte Long Stay",
    price: 799,
    image: Lipstick,
    rating: 4,
    reviews: 36,
    imageUrl: " ",
    category: "Eyeliner",
    color: "bg-pink-400",
    shade: "Pink",
    dresStyle: "Gym",
    brands: "Lakme",
    discount: 20,
    material: "Hard",
    quantity:1,
  },
];

export default productDetails;
