const navItemData = {
  "Face care": [
    {"Cleansers": ["Face wash","Cleaning oil","Cleansing wipes","Micellar water",]},
    {"Moisturizers": ["Gel", "Cream", "Lotion", "Face oils"]},
    {"Toners": ["Hydrating toners", "Stringent toners"]},
    {"Exfoliants": ["Scrubs", "Chemical exfoliants", "Enzyme"]},
    {"Masks": ["Sheet masks","Clay masks","Peels-off masks","Overnight masks"]},
    {"Eye Care": ["Eye gel", "Eye Cream", "Eye serums"]},
  ],
  "Skin Care": [
    {"Cleanser": ["Face wash","Cleaning oil","Cleansing wipes","Micellar water"]},
    {"Moisturizers": ["Gel", "Cream", "Lotion", "Face oils"]},
    {"Toners": ["Hydrating toners", "Stringent toners"]},
    {"Masks": ["Sheet masks","Clay masks","Peels-off masks","Overnight masks"]},
    {"Eye Care": ["Eye gel", "Eye Cream", "Eye serums"]},
    {"Sunscreens": ["Physical sunscreens", "Chemical sunscreens"]},
    {"Serum": ["Hydrating","Anti-Aging serums","Brightening serums","Acne treatment serums"]},
    {"Exfoliants": ["Scrubs", "Chemical exfoliants", "Enzyme"]},
    {"Speciality products": ["Anti-pollution SkinCare", "Hydrating mists"]},
  ],
  "Hair Care": [
    {"Styling": ["Hair gel", "Hair Spray", "Serum & Oil"]},
    {"Cleansing": ["Shampoo"]},
    {"Conditioning": ["Conditioner"]},
    {"Hair Masks": ["Deep conditioning masks","Hair growth masks","Color protecting masks"]},
    {"Hair Oils": ["Coconut oil", "Argan oil", "Olive oil"]},
    {"Hair Accessories": ["Hair ties", "Hair clips", "Hair bands"]},
  ],
  "Makeup": [
    {"Face Products": ["Foundation","Primer","Concealer","Compact Powder","Loose Powder","Blush","Bronzer","Highlighter"]},
    {"Eye products": ["Eyeshadow","Eyeshadow primer","Eyeliner","Mascara","Eyebrow pencil","Eyebrow gel"]},
    {"Other products": ["Setting spray","Makeup remover","Contour kits","Eyelashes","Brushes"]},
    {"Lip products": ["Lipstick", "Lip gloss", "Lip Liner", "Lip balm"]},
    {"Nail products": ["Nail polish", "Nail glue", "Nail files"]},
    {"Tools": ["Makeup brushes", "Makeup sponges", "Tweezers"]},
  ],
  "Body Care": [
    {"Cleansing products": ["Body wash", "Bar soap", "Scrubs", "Bath salts"]},
    {"Speciality products": ["Massage oils", "Foot creams", "Hand creams", "Body masks",]},
    {"Moisturizing products": ["Body lotion", "Body butter", "Body oil"],},
    {"Hair removal products": ["Shaving cream", "Shaving gel", "Wax kits"]},
    {"Fragrance products": ["Body spray", "Body mist"]},
    {"Protection products": ["sunscreen"]},
    {"Hygiene products": ["Deodorant", "Antiperspirant"]},
    {"Wellness products": ["Body scrubs", "Body wraps"]},
  ],
  "Fragrance": [
    {"Perfumes": ["Floral", "Oriental", "Woody", "Fresh"]},
    {"Colognes": ["Citrus", "Oriental", "Woody", "Fresh"]},
    {"Deodorants": ["Stick", "Roll-on", "Spray"]},
  ],
  "Combos": [
      {"SkinCare Combos": ["Face wash and moisturizer", "Toner and serum"]},
      {"HairCare Combos": ["Shampoo and conditioner", "Hair mask and oil"]},
      {"Makeup Combos": ["Foundation and concealer", "Eyeshadow and eyeliner"]},
  ],
  "Natural": [
      {"Natural Skin Care": ["Face wash", "Moisturizer", "Toner"]},
      {"Natural Hair Care": ["Shampoo", "Conditioner", "Hair oil"]},
      {"Natural Makeup": ["Foundation", "Eyeshadow", "Lipstick"]},
  ],
  "Health & Wellness": [
      {"Supplements": ["Vitamins", "Proteins", "Minerals"]},
      {"Fitness": ["Yoga mats", "Dumbbells", "Fitness trackers"]},
      {"HealthyFood": ["Protein powder", "Healthy snacks", "Supplements"]},
  ],
  "Nail Care": [
    {"Nail polishes": ["Regular nail polishes","Gel nail polishes","Matte nail polishes","Glitter nail polishes"]},
    {"Nail remover": ["Nail polish remover","Gel polish remover","Nail wraps"]},
    {"other products": ["Nail files", "Nail clippers", "Nail glue"]},
  ],
};
export default navItemData;
